### ISSUE TITLE
Recschedule url being outdated

### ISSUE THREAD

**Issue by aoranwu** [williamshen-nz/recschedule-website#4]
Hi William,

It looks like the original url for recschedule (http://web.mit.edu/athletics/www/recschedule.pdf) stops getting updated now. The new schedule is now at https://www.mitrecsports.com/assets/Open-Rec-1.13.2023-1.22.23.pdf but the filename seems to be date-related. Do you think you can get the script working for this?

Thanks,
Aoran

**Comment by williamshen-nz** [comment]
Hi Aoran, thanks for the report.

Working on the changes here: https://github.com/williamshen-nz/recschedule-website/pull/5

Just need to scrape MIT Rec website for the URL and then it's same as before

**Comment by williamshen-nz** [comment]
Deployed, had to set use unsecured https for some reason.

@aoranwu could you please keep an eye on the website and let me know if there's any issues?

**Comment by aoranwu** [comment]
That's awesome, thanks for the fix! I'm an active user of this website and I'll let you know if I see any problem happening
