### ISSUE TITLE
Change schedule parsing

### ISSUE THREAD

**Issue by robinlin99** [williamshen-nz/recschedule-website#8]
MIT Rec no longer uses PDFs for presenting open recreation schedule. Instead, they have replaced it with Mazevo calendar (i.e https://east.mymazevo.com/calendar?code=RXphMEplcUJrNXhtelI0WitsVXJMK1Q5YmpWaTlJQkprZmYwVVhsOW94cm92aDJGcWNFYklMUzNtZ1h5Qmg2UnMwS2tCU0dBa1ZlMEZ0azNmbHptdUdYbGgvZW90MXExVWR2dXVJN1ovK3BoQm9uR0pndkpuMmU1bnp1bm5CcmM). The current schedule parsing will no longer work.

**Comment by williamshen-nz** [comment]
Thanks for bringing this up! Contributions are welcome as I no longer play badminton frequently.

It looks like Mazevo has a GetEvents POST API which could be used which returns a list of bookings in a structured format.

https://east.mymazevo.com/api/PublicCalendar/GetEvents

![image](https://github.com/user-attachments/assets/429cccf9-36e6-4951-b2a6-b28b7c5f1945)

**Comment by williamshen-nz** [comment]
I just updated the website to note the new Mazevo calendar and have embedded it as an `iframe` in the meantime.

![Screenshot 2024-08-13 at 12 19 17 PM](https://github.com/user-attachments/assets/0dfc13cf-2efa-4297-9b3a-fc37fb3630c3)

**Comment by williamshen-nz** [comment]
The website has been updated to pull from the Mazevo API and then parse the responses! 

All previously functionality including shared sessions has been maintained: https://shen.nz/badminton/
